"""
Agent Zero Project Management CLI
Initialize, scaffold, and manage Agent Zero projects
"""

import json
import shutil
from pathlib import Path
from typing import Optional
from datetime import datetime

import typer
from rich.console import Console
from rich.panel import Panel
from rich.tree import Tree
from rich.progress import Progress, SpinnerColumn, TextColumn

project_app = typer.Typer(help="Project management and scaffolding")
console = Console()


TEMPLATES = {
    "default": {
        "description": "Standard Agent Zero project",
        "structure": {
            "agents": ["custom_agent.py"],
            "prompts": ["custom"],
            "tools": ["custom_tool.py"],
            "knowledge": ["custom"],
            "work_dir": [],
        }
    },
    "minimal": {
        "description": "Minimal project setup",
        "structure": {
            "work_dir": [],
        }
    },
    "research": {
        "description": "Research-oriented project with web search and analysis",
        "structure": {
            "agents": ["researcher.py", "analyzer.py"],
            "prompts": ["research"],
            "tools": ["web_search.py", "document_analyzer.py"],
            "knowledge": ["research"],
            "work_dir": [],
        }
    },
    "code": {
        "description": "Code-focused project for development tasks",
        "structure": {
            "agents": ["code_expert.py"],
            "prompts": ["code"],
            "tools": ["code_analyzer.py", "git_tool.py"],
            "knowledge": ["code"],
            "work_dir": ["src", "tests"],
        }
    },
}


def init_project(name: str, template: str, target_path: Path):
    """Initialize a new Agent Zero project"""

    if template not in TEMPLATES:
        console.print(f"[red]Unknown template: {template}[/red]")
        console.print(f"[yellow]Available templates: {', '.join(TEMPLATES.keys())}[/yellow]")
        raise typer.Exit(1)

    template_config = TEMPLATES[template]

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console
    ) as progress:
        task = progress.add_task(f"Creating project {name}...", total=100)

        # Create project directory
        progress.update(task, advance=10, description="Creating directories...")
        target_path.mkdir(parents=True, exist_ok=True)

        # Create structure
        structure = template_config["structure"]
        total_items = sum(len(items) if items else 1 for items in structure.values())
        advance_per_item = 70 / max(total_items, 1)

        for directory, files in structure.items():
            dir_path = target_path / directory
            dir_path.mkdir(parents=True, exist_ok=True)

            if files:
                for file in files:
                    if file.endswith(".py"):
                        file_path = dir_path / file
                        file_path.write_text(_generate_python_template(name, file))
                    else:
                        # Create directory
                        (dir_path / file).mkdir(parents=True, exist_ok=True)

                    progress.update(task, advance=advance_per_item)

        # Create configuration files
        progress.update(task, advance=10, description="Creating configuration...")
        _create_config_files(target_path, name, template)

        # Create README
        progress.update(task, advance=5, description="Creating documentation...")
        _create_readme(target_path, name, template)

        progress.update(task, advance=5, description="Finalizing...")

    console.print(f"\n[bold green]✓ Project '{name}' created successfully![/bold green]")
    console.print(f"[dim]Location: {target_path}[/dim]\n")

    # Show next steps
    console.print(Panel(
        f"[bold cyan]Next Steps:[/bold cyan]\n\n"
        f"1. cd {target_path.name}\n"
        f"2. agent-zero config init\n"
        f"3. agent-zero chat\n\n"
        f"[dim]Or start with: agent-zero run \"your task\"[/dim]",
        title="Getting Started",
        border_style="green"
    ))


def _generate_python_template(project_name: str, filename: str) -> str:
    """Generate Python file template"""
    class_name = filename.replace(".py", "").replace("_", " ").title().replace(" ", "")

    return f'''"""
{project_name} - {filename}
Auto-generated by Agent Zero CLI
"""

from python.helpers.tool import Tool, Response


class {class_name}(Tool):
    """
    Custom tool for {project_name}

    Generated from template: {filename}
    """

    async def execute(self, **kwargs):
        """Execute the tool"""

        # Get parameters
        task = self.args.get("task", "")

        # Your implementation here
        result = f"Executing {{task}} with {class_name}"

        return Response(
            message=result,
            break_loop=False
        )
'''


def _create_config_files(target_path: Path, name: str, template: str):
    """Create project configuration files"""

    # Create .env template
    env_content = """# Agent Zero Configuration
# Copy this to .env and fill in your API keys

# AI Provider (google, openai, anthropic, ollama)
AI_PROVIDER=google

# API Keys
GOOGLE_API_KEY=your_key_here
OPENAI_API_KEY=your_key_here
ANTHROPIC_API_KEY=your_key_here

# Model Configuration
CHAT_MODEL=gemini-2.5-flash
UTILITY_MODEL=gemini-2.5-flash
EMBEDDING_MODEL=models/embedding-001

# Agent Configuration
MAX_ITERATIONS=10
RATE_LIMIT=30
AUTO_MEMORY=false
"""
    (target_path / ".env.template").write_text(env_content)

    # Create project config
    project_config = {
        "name": name,
        "version": "1.0.0",
        "template": template,
        "created_at": datetime.now().isoformat(),
        "agent_zero_version": "2.0.0",
        "configuration": {
            "prompts_subdir": "",
            "memory_subdir": name,
            "knowledge_subdirs": ["default", name],
        }
    }

    (target_path / "project.json").write_text(json.dumps(project_config, indent=2))

    # Create .gitignore
    gitignore_content = """# Agent Zero
.env
work_dir/
*.log
*.db
__pycache__/
*.pyc
.DS_Store
memory/
"""
    (target_path / ".gitignore").write_text(gitignore_content)


def _create_readme(target_path: Path, name: str, template: str):
    """Create project README"""

    readme_content = f"""# {name}

Agent Zero project created from the '{template}' template.

## Description

{TEMPLATES[template]['description']}

## Setup

1. Install dependencies:
```bash
pip install -r requirements.txt
```

2. Configure environment:
```bash
cp .env.template .env
# Edit .env with your API keys
```

3. Initialize configuration:
```bash
agent-zero config init
```

## Usage

Start interactive chat:
```bash
agent-zero chat
```

Run a single task:
```bash
agent-zero run "your task here"
```

## Project Structure

```
{name}/
├── agents/          # Custom agents
├── prompts/         # Custom prompts
├── tools/           # Custom tools
├── knowledge/       # Knowledge base
├── work_dir/        # Working directory
├── project.json     # Project configuration
└── .env            # Environment variables
```

## Development

Start development mode with hot reload:
```bash
agent-zero dev
```

## Deployment

Deploy to various platforms:
```bash
agent-zero deploy local
agent-zero deploy cloud
agent-zero deploy mobile
```

## Documentation

- [Agent Zero Documentation](https://agent-zero.io/docs)
- [CLI Reference](https://agent-zero.io/docs/cli)
- [Template Guide](https://agent-zero.io/docs/templates/{template})

## License

MIT

---
Generated by Agent Zero CLI 2.0
"""

    (target_path / "README.md").write_text(readme_content)


@project_app.command("init")
def init(
    name: str = typer.Argument(..., help="Project name"),
    template: str = typer.Option("default", "--template", "-t", help="Project template"),
    path: Optional[str] = typer.Option(None, "--path", "-p", help="Target directory"),
):
    """Initialize a new Agent Zero project"""
    target_path = Path(path) if path else Path.cwd() / name
    init_project(name, template, target_path)


@project_app.command("templates")
def list_templates():
    """List available project templates"""

    table_data = []
    for name, config in TEMPLATES.items():
        table_data.append((name, config["description"]))

    # Create tree view
    tree = Tree("[bold cyan]Available Templates[/bold cyan]")

    for name, description in table_data:
        branch = tree.add(f"[green]{name}[/green]")
        branch.add(f"[dim]{description}[/dim]")

        # Show structure
        structure = TEMPLATES[name]["structure"]
        struct_branch = branch.add("[yellow]Structure:[/yellow]")
        for dir_name, items in structure.items():
            if items:
                dir_branch = struct_branch.add(f"📁 {dir_name}/")
                for item in items[:3]:  # Show first 3 items
                    dir_branch.add(f"{'📄' if item.endswith('.py') else '📁'} {item}")
                if len(items) > 3:
                    dir_branch.add(f"[dim]... and {len(items) - 3} more[/dim]")
            else:
                struct_branch.add(f"📁 {dir_name}/")

    console.print(tree)
    console.print(f"\n[dim]Use: agent-zero init <name> --template <template>[/dim]")


@project_app.command("info")
def project_info(
    path: str = typer.Option(".", "--path", "-p", help="Project directory"),
):
    """Show project information"""

    project_path = Path(path)
    config_file = project_path / "project.json"

    if not config_file.exists():
        console.print(f"[yellow]No project.json found in {path}[/yellow]")
        console.print("[dim]This doesn't appear to be an Agent Zero project[/dim]")
        return

    config = json.loads(config_file.read_text())

    info_panel = f"""[bold cyan]{config['name']}[/bold cyan]

[yellow]Version:[/yellow] {config.get('version', 'N/A')}
[yellow]Template:[/yellow] {config.get('template', 'custom')}
[yellow]Created:[/yellow] {config.get('created_at', 'N/A')}
[yellow]Agent Zero Version:[/yellow] {config.get('agent_zero_version', 'N/A')}

[bold]Configuration:[/bold]
{json.dumps(config.get('configuration', {}), indent=2)}

[bold]Location:[/bold]
[dim]{project_path.absolute()}[/dim]
"""

    console.print(Panel(info_panel, title="Project Information", border_style="cyan"))


@project_app.command("validate")
def validate_project(
    path: str = typer.Option(".", "--path", "-p", help="Project directory"),
):
    """Validate project structure"""

    project_path = Path(path)
    config_file = project_path / "project.json"

    errors = []
    warnings = []

    # Check project.json
    if not config_file.exists():
        errors.append("project.json not found")
    else:
        try:
            config = json.loads(config_file.read_text())
            if "name" not in config:
                errors.append("project.json missing 'name' field")
        except json.JSONDecodeError:
            errors.append("project.json is not valid JSON")

    # Check .env
    if not (project_path / ".env").exists():
        if not (project_path / ".env.template").exists():
            warnings.append(".env and .env.template not found")
        else:
            warnings.append(".env not found (template exists)")

    # Check required directories
    recommended_dirs = ["agents", "prompts", "tools", "work_dir"]
    for dir_name in recommended_dirs:
        if not (project_path / dir_name).exists():
            warnings.append(f"Recommended directory '{dir_name}' not found")

    # Display results
    if errors:
        console.print("\n[bold red]Errors:[/bold red]")
        for error in errors:
            console.print(f"  [red]✗[/red] {error}")

    if warnings:
        console.print("\n[bold yellow]Warnings:[/bold yellow]")
        for warning in warnings:
            console.print(f"  [yellow]⚠[/yellow] {warning}")

    if not errors and not warnings:
        console.print("[green]✓ Project structure is valid[/green]")
    elif errors:
        raise typer.Exit(1)


@project_app.command("clean")
def clean_project(
    path: str = typer.Option(".", "--path", "-p", help="Project directory"),
    deep: bool = typer.Option(False, "--deep", help="Deep clean (remove logs, memory, etc.)"),
):
    """Clean project artifacts"""

    project_path = Path(path)

    items_to_clean = [
        "__pycache__",
        "*.pyc",
        "*.log",
    ]

    if deep:
        items_to_clean.extend([
            "memory",
            "*.db",
            ".agent-zero-cache",
        ])

    removed_count = 0

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console
    ) as progress:
        task = progress.add_task("Cleaning project...", total=None)

        for pattern in items_to_clean:
            if "*" in pattern:
                # Glob pattern
                for item in project_path.rglob(pattern):
                    if item.is_file():
                        item.unlink()
                        removed_count += 1
            else:
                # Directory name
                for item in project_path.rglob(pattern):
                    if item.is_dir():
                        shutil.rmtree(item)
                        removed_count += 1

    console.print(f"[green]✓ Cleaned {removed_count} items[/green]")


if __name__ == "__main__":
    project_app()
